export APP=jiameng-api

if [ "$GIT_BRANCH" == "develop" ]; then
    export ENV=dev
    export DOMAIN_PREFIX=dev.
    export CLUSTER_NAME=staging
    export AWS_ACCESS_KEY_ID=$STAGING_CODEBUILD_AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$STAGING_CODEBUILD_AWS_SECRET_ACCESS_KEY
    export GO_APP_AWS_ACCESS_KEY_ID=$STAGING_GO_APP_AWS_ACCESS_KEY_ID
    export GO_APP_AWS_SECRET_ACCESS_KEY=$STAGING_GO_APP_AWS_SECRET_ACCESS_KEY
    export AWS_ACCOUNT_ID=$STAGING_ACCOUNT_ID
fi
if [ "$CODEBUILD_GIT_BRANCH" == "qa" ]; then
    export ENV=qa
    export DOMAIN_PREFIX=qa.
    export CLUSTER_NAME=staging
    export AWS_ACCESS_KEY_ID=${STAGING_CIRCLECI_AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${STAGING_CIRCLECI_AWS_SECRET_ACCESS_KEY}
    export GO_APP_AWS_ACCESS_KEY_ID=${STAGING_GO_APP_AWS_ACCESS_KEY_ID}
    export GO_APP_AWS_SECRET_ACCESS_KEY=${STAGING_GO_APP_AWS_SECRET_ACCESS_KEY}
    export AWS_ACCOUNT_ID=${STAGING_ACCOUNT_ID}
fi
if [ "$CODEBUILD_GIT_BRANCH" == "demo" ]; then
    export ENV=demo
    export DOMAIN_PREFIX=demo.
    export CLUSTER_NAME=staging
    export AWS_ACCESS_KEY_ID=${STAGING_CIRCLECI_AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${STAGING_CIRCLECI_AWS_SECRET_ACCESS_KEY}
    export GO_APP_AWS_ACCESS_KEY_ID=${STAGING_GO_APP_AWS_ACCESS_KEY_ID}
    export GO_APP_AWS_SECRET_ACCESS_KEY=${STAGING_GO_APP_AWS_SECRET_ACCESS_KEY}
    export AWS_ACCOUNT_ID=${STAGING_ACCOUNT_ID}
fi
if [ "$CODEBUILD_GIT_BRANCH" == "main" ]; then
    export ENV=prod
    export DOMAIN_PREFIX=
    export CLUSTER_NAME=prod
    export AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
    export AWS_ACCOUNT_ID=${PROD_ACCOUNT_ID}
fi
if [ "$CODEBUILD_GIT_BRANCH" == "preprod" ]; then
    export ENV=preprod
    export DOMAIN_PREFIX=preprod.
    export CLUSTER_NAME=prod
    export AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
    export AWS_ACCOUNT_ID=${PROD_ACCOUNT_ID}
fi
